services:
  app:
    build: .
    deploy:
      replicas: 2
    ports:
      - "8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
    networks:
      - my-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - my-network

  load_balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - my-network
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
